GH Action & error-handling.gv
rust-lang/project-error-handling pull request #48
Opened 2021-08-03 16:15 UTC by nagashi

The GH Action will conditionally execute on a push or pull_request if 
error-handling.gv has been modified.  If it has, a SVG file will be created and uploaded as an artifact.  Additionally, the title in the error-handling.gv file has been recoded so that the title appears at the top of the form, when viewed, and will now be bolded.

2021-08-03 17:55 UTC, yaahc reviewed
This looks really good, we just need to change the last step from upload to comparison then it should be good to merge.

2021-08-03 17:55 UTC, yaahc commented on .github/workflows/check_graphviz_source.yml
> +          retention-days: 30
instead of `upload-artifact` I think we want to just run `cmp error-handling-artifact.svg error-handling.svg`

2021-08-03 20:39 UTC, yaahc requested changes
Since we're generating the svg in the action and saving it we shouldn't also commit the original version of the svg. Can you remove that file from git and then change the action to generate a file named `error-handling.svg` instead of `new-error-handling.svg`?

2021-08-05 16:56 UTC, nagashi commented
> Since we're generating the svg in the action and saving it we shouldn't also commit the original version of the svg. Can you remove that file from git and then change the action to generate a file named `error-handling.svg` instead of `new-error-handling.svg`?

This request is now completed.

2021-08-05 18:07 UTC, yaahc approved these changes

2021-08-05 18:09 UTC, merged